-- Optional one-time seed for the current Buy & Sell GH catalogue.
-- Upload final product images to Supabase Storage first, then replace [] image arrays
-- with public image URLs if you want Supabase to own the image references too.
-- Stable IDs/slugs plus ON CONFLICT make this safe to rerun without duplicates.

insert into public.products (
  id, slug, name, brand, category, subcategory, model, generation, description,
  short_description, price, previous_price, price_on_request, condition,
  storage_options, colour_options, default_colour, battery_health, warranty,
  stock_quantity, stock_status, featured, new_arrival, popular, available,
  images, primary_image, specifications, included_items, delivery_information,
  tags, archived
) values
  (
    'iphone-16-pro-max',
    'iphone-16-pro-max',
    'iPhone 16 Pro Max',
    'Apple',
    'Brand New Devices',
    null,
    'iPhone 16 Pro Max',
    null,
    'A flagship Apple device with premium performance, strong camera features and elegant titanium finishes.',
    'A flagship Apple device with premium performance, strong camera features and elegant titanium finishes.',
    20500,
    21800,
    false,
    'Brand New',
    '["256GB","512GB","1TB"]'::jsonb,
    '["Desert Titanium","Natural Titanium","Black Titanium"]'::jsonb,
    'Desert Titanium',
    null,
    'Warranty terms are confirmed per unit before payment.',
    2,
    'Low Stock',
    true,
    true,
    true,
    true,
    '[]'::jsonb,
    0,
    '["6.9-inch Super Retina XDR display","A18 Pro chip","Pro camera system","USB-C charging"]'::jsonb,
    '["Device","USB-C cable","SIM pin where applicable"]'::jsonb,
    'Pickup in Dome or delivery options can be confirmed on WhatsApp.',
    '["iphone","iphone 16","pro max","titanium","brand new","limited stock"]'::jsonb,
    false
  ),
  (
    'iphone-16-pro',
    'iphone-16-pro',
    'iPhone 16 Pro',
    'Apple',
    'Brand New Devices',
    null,
    'iPhone 16 Pro',
    null,
    'Compact Pro iPhone for customers who want flagship speed, cameras and a premium Apple feel.',
    'Compact Pro iPhone for customers who want flagship speed, cameras and a premium Apple feel.',
    17800,
    null,
    false,
    'Brand New',
    '["128GB","256GB","512GB"]'::jsonb,
    '["Natural Titanium","White Titanium","Black Titanium"]'::jsonb,
    'Natural Titanium',
    null,
    'Warranty terms are confirmed per unit before payment.',
    4,
    'In Stock',
    false,
    true,
    true,
    true,
    '[]'::jsonb,
    0,
    '["6.3-inch Super Retina XDR display","A18 Pro chip","ProMotion display","USB-C charging"]'::jsonb,
    '["Device","USB-C cable"]'::jsonb,
    'Pickup and delivery options are confirmed before an order request is finalized.',
    '["iphone","iphone 16 pro","128gb","256gb","titanium","brand new"]'::jsonb,
    false
  ),
  (
    'iphone-15-pro-max',
    'iphone-15-pro-max',
    'iPhone 15 Pro Max',
    'Apple',
    'iPhones',
    null,
    'iPhone 15 Pro Max',
    null,
    'A high-demand UK used option with strong battery choices and Pro Max camera quality.',
    'A high-demand UK used option with strong battery choices and Pro Max camera quality.',
    14500,
    15500,
    false,
    'UK Used',
    '["256GB","512GB"]'::jsonb,
    '["Natural Titanium","Blue Titanium","Black Titanium"]'::jsonb,
    'Natural Titanium',
    '90%+ options available, confirm selected unit',
    'Contact the shop to confirm warranty for the selected unit.',
    5,
    'In Stock',
    false,
    false,
    true,
    true,
    '[]'::jsonb,
    0,
    '["6.7-inch Super Retina XDR display","A17 Pro chip","Titanium design","Action Button"]'::jsonb,
    '["Device","Charging cable where available"]'::jsonb,
    'Pickup in Dome or delivery options can be discussed on WhatsApp.',
    '["iphone","iphone 15 pro max","256gb","512gb","natural titanium","uk used"]'::jsonb,
    false
  ),
  (
    'iphone-15',
    'iphone-15',
    'iPhone 15',
    'Apple',
    'iPhones',
    null,
    'iPhone 15',
    null,
    'A clean everyday iPhone for buyers who want modern Apple features at a balanced price.',
    'A clean everyday iPhone for buyers who want modern Apple features at a balanced price.',
    9800,
    null,
    false,
    'Excellent',
    '["128GB","256GB"]'::jsonb,
    '["Pink","Blue","Black","Green"]'::jsonb,
    'Pink',
    'Confirm selected unit',
    'Warranty terms are confirmed per unit before purchase.',
    7,
    'In Stock',
    false,
    true,
    false,
    true,
    '[]'::jsonb,
    0,
    '["6.1-inch Super Retina XDR display","Dynamic Island","48MP main camera","USB-C charging"]'::jsonb,
    '["Device","Charging cable where available"]'::jsonb,
    'Pickup and delivery details are confirmed on WhatsApp.',
    '["iphone 15","128gb","256gb","pink","blue","excellent"]'::jsonb,
    false
  ),
  (
    'iphone-14-pro-max',
    'iphone-14-pro-max',
    'iPhone 14 Pro Max',
    'Apple',
    'UK Used Devices',
    null,
    'iPhone 14 Pro Max',
    null,
    'Popular Pro Max option with a large display, strong battery life and premium build.',
    'Popular Pro Max option with a large display, strong battery life and premium build.',
    11200,
    null,
    false,
    'UK Used',
    '["128GB","256GB","512GB"]'::jsonb,
    '["Deep Purple","Gold","Silver","Space Black"]'::jsonb,
    'Deep Purple',
    '88%+ options available, confirm selected unit',
    'Contact the shop to confirm warranty for the selected unit.',
    2,
    'Low Stock',
    false,
    false,
    true,
    true,
    '[]'::jsonb,
    0,
    '["6.7-inch Super Retina XDR display","A16 Bionic chip","Dynamic Island","Pro camera system"]'::jsonb,
    '["Device","Charging cable where available"]'::jsonb,
    'Pickup in Dome or delivery options can be discussed on WhatsApp.',
    '["iphone 14 pro max","uk used","deep purple","gold","128gb","256gb"]'::jsonb,
    false
  ),
  (
    'iphone-13-pro-max',
    'iphone-13-pro-max',
    'iPhone 13 Pro Max',
    'Apple',
    'UK Used Devices',
    null,
    'iPhone 13 Pro Max',
    null,
    'Strong value Pro Max option for buyers who want size, camera quality and reliable performance.',
    'Strong value Pro Max option for buyers who want size, camera quality and reliable performance.',
    8200,
    null,
    false,
    'Very Good',
    '["128GB","256GB"]'::jsonb,
    '["Sierra Blue","Gold","Graphite"]'::jsonb,
    'Sierra Blue',
    '85%+ options available, confirm selected unit',
    'Contact the shop to confirm warranty for the selected unit.',
    6,
    'In Stock',
    false,
    false,
    true,
    true,
    '[]'::jsonb,
    0,
    '["6.7-inch Super Retina XDR display","A15 Bionic chip","120Hz ProMotion","Triple camera system"]'::jsonb,
    '["Device"]'::jsonb,
    'Pickup and delivery options are confirmed before an order request is finalized.',
    '["iphone 13 pro max","uk used","sierra blue","gold","128gb","256gb"]'::jsonb,
    false
  ),
  (
    'iphone-12-pro-max',
    'iphone-12-pro-max',
    'iPhone 12 Pro Max',
    'Apple',
    'UK Used Devices',
    null,
    'iPhone 12 Pro Max',
    null,
    'Large-display UK used option for customers upgrading on a careful budget.',
    'Large-display UK used option for customers upgrading on a careful budget.',
    6400,
    null,
    false,
    'Very Good',
    '["128GB","256GB"]'::jsonb,
    '["Pacific Blue","Gold","Graphite"]'::jsonb,
    'Pacific Blue',
    'Varies by unit',
    'Contact the shop to confirm warranty for the selected unit.',
    1,
    'Low Stock',
    false,
    false,
    false,
    true,
    '[]'::jsonb,
    0,
    '["6.7-inch Super Retina XDR display","A14 Bionic chip","5G capable","MagSafe support"]'::jsonb,
    '["Device"]'::jsonb,
    'Pickup and delivery details are confirmed on WhatsApp.',
    '["iphone 12 pro max","uk used","pacific blue","gold","128gb","low stock"]'::jsonb,
    false
  ),
  (
    'iphone-11-pro-max',
    'iphone-11-pro-max',
    'iPhone 11 Pro Max',
    'Apple',
    'UK Used Devices',
    null,
    'iPhone 11 Pro Max',
    null,
    'Budget-friendly Pro Max option for buyers who want a premium Apple experience at a lower price.',
    'Budget-friendly Pro Max option for buyers who want a premium Apple experience at a lower price.',
    4700,
    null,
    false,
    'Very Good',
    '["64GB","256GB"]'::jsonb,
    '["Midnight Green","Space Gray","Gold"]'::jsonb,
    'Midnight Green',
    'Restock details to confirm',
    'Warranty terms will be confirmed when the device is available.',
    0,
    'Sold',
    false,
    false,
    false,
    false,
    '[]'::jsonb,
    0,
    '["6.5-inch Super Retina XDR display","A13 Bionic chip","Triple camera system","Face ID"]'::jsonb,
    '["Device"]'::jsonb,
    'Customers can request restock through WhatsApp.',
    '["iphone 11 pro max","uk used","midnight green","64gb","sold out"]'::jsonb,
    false
  ),
  (
    'ipad-pro',
    'ipad-pro',
    'iPad Pro',
    'Apple',
    'iPads',
    null,
    'iPad Pro',
    null,
    'Premium iPad option for work, design, school and entertainment.',
    'Premium iPad option for work, design, school and entertainment.',
    13800,
    null,
    false,
    'Excellent',
    '["256GB","512GB"]'::jsonb,
    '["Silver","Space Black"]'::jsonb,
    'Silver',
    null,
    'Warranty terms are confirmed per unit before purchase.',
    2,
    'Low Stock',
    false,
    true,
    false,
    true,
    '[]'::jsonb,
    0,
    '["Liquid Retina display","Apple Pencil support","USB-C charging","Wi-Fi options"]'::jsonb,
    '["iPad","Charging cable where available"]'::jsonb,
    'Pickup and delivery options are confirmed on WhatsApp.',
    '["ipad","ipad pro","256gb","512gb","silver","space black"]'::jsonb,
    false
  ),
  (
    'apple-watch',
    'apple-watch',
    'Apple Watch',
    'Apple',
    'Apple Watches',
    null,
    'Apple Watch',
    null,
    'Apple Watch option for fitness, notifications and everyday convenience.',
    'Apple Watch option for fitness, notifications and everyday convenience.',
    2600,
    null,
    false,
    'Excellent',
    '["GPS","GPS + Cellular"]'::jsonb,
    '["Midnight","Silver","Starlight"]'::jsonb,
    'Midnight',
    null,
    'Warranty terms are confirmed per unit before purchase.',
    8,
    'In Stock',
    false,
    false,
    true,
    true,
    '[]'::jsonb,
    0,
    '["Health tracking","Workout modes","Water resistance","iPhone pairing"]'::jsonb,
    '["Watch","Band","Charging cable where available"]'::jsonb,
    'Pickup and delivery options are confirmed on WhatsApp.',
    '["apple watch","watch","gps","cellular","midnight","silver"]'::jsonb,
    false
  ),
  (
    'airpods-pro',
    'airpods-pro',
    'AirPods Pro',
    'Apple',
    'AirPods',
    null,
    'AirPods Pro',
    null,
    'Original AirPods Pro option for crisp audio, noise control and Apple ecosystem convenience.',
    'Original AirPods Pro option for crisp audio, noise control and Apple ecosystem convenience.',
    2200,
    null,
    false,
    'Brand New',
    '["USB-C Case"]'::jsonb,
    '["White"]'::jsonb,
    'White',
    null,
    'Warranty terms are confirmed before purchase.',
    10,
    'In Stock',
    false,
    true,
    false,
    true,
    '[]'::jsonb,
    0,
    '["Active Noise Cancellation","Transparency mode","USB-C case","Spatial audio support"]'::jsonb,
    '["AirPods Pro","Charging case","Ear tips","Cable"]'::jsonb,
    'Pickup and delivery options are confirmed on WhatsApp.',
    '["airpods","airpods pro","usb-c","white","brand new"]'::jsonb,
    false
  )
on conflict (slug) do update set
  id = excluded.id,
  name = excluded.name,
  brand = excluded.brand,
  category = excluded.category,
  subcategory = excluded.subcategory,
  model = excluded.model,
  generation = excluded.generation,
  description = excluded.description,
  short_description = excluded.short_description,
  price = excluded.price,
  previous_price = excluded.previous_price,
  price_on_request = excluded.price_on_request,
  condition = excluded.condition,
  storage_options = excluded.storage_options,
  colour_options = excluded.colour_options,
  default_colour = excluded.default_colour,
  battery_health = excluded.battery_health,
  warranty = excluded.warranty,
  stock_quantity = excluded.stock_quantity,
  stock_status = excluded.stock_status,
  featured = excluded.featured,
  new_arrival = excluded.new_arrival,
  popular = excluded.popular,
  available = excluded.available,
  images = case
    when jsonb_array_length(public.products.images) > 0 then public.products.images
    else excluded.images
  end,
  primary_image = excluded.primary_image,
  specifications = excluded.specifications,
  included_items = excluded.included_items,
  delivery_information = excluded.delivery_information,
  tags = excluded.tags,
  archived = excluded.archived,
  updated_at = now();
