import type { ProductFamilyKey } from "../../../catalog/productExperience";
import macStudioLaunchImage from "../../../assets/homepage/homepage-mac-studio-m5-launch.webp";
import { localCatalogueImageBySlug } from "../../../utils/catalogueProductImages";

export interface CategorySubnavItem {
  id: string;
  label: string;
  icon?: string;
}

export interface CategoryFeaturedCardData {
  id: string;
  eyebrow: string;
  title: string;
  subtitle: string;
  price: string;
  badge?: string;
  image: string;
  alt: string;
  buyPath: string;
  buyLabel?: string;
  storyPath?: string;
  storyLabel?: string;
  isDark?: boolean;
  isViewPricingOnly?: boolean;
}

export interface CategoryDepartmentConfig {
  key: ProductFamilyKey;
  label: string;
  tagline: string;
  description: string;
  seoTitle: string;
  seoDescription: string;
  subnavItems: CategorySubnavItem[];
  featuredCards: CategoryFeaturedCardData[];
  catalogTitle: string;
  catalogSubtitle: string;
  storeCategoryFilter: string;
}

export const CATEGORY_DEPARTMENTS: Record<ProductFamilyKey, CategoryDepartmentConfig> = {
  iphone: {
    key: "iphone",
    label: "iPhone",
    tagline: "The best way to buy the iPhone you love.",
    description: "Explore the latest flagship models, confirmed storage configurations, and certified UK Used iPhones with verified battery health.",
    seoTitle: "Shop iPhone | Buy & Sell GH Store",
    seoDescription: "Browse genuine iPhone models in Ghana. iPhone 18 Pro, iPhone Duo, iPhone 16 & 15 series, and certified UK Used iPhones with local warranty.",
    subnavItems: [
      { id: "all", label: "All iPhone" },
      { id: "pro", label: "iPhone Pro Models" },
      { id: "standard", label: "iPhone Standard & Plus" },
      { id: "duo", label: "iPhone Duo" },
      { id: "uk-used", label: "Certified UK Used" },
    ],
    featuredCards: [
      {
        id: "iphone-18-pro",
        eyebrow: "FLAGSHIP TITANIUM",
        title: "iPhone 18 Pro",
        subtitle: "Cinematic pro camera system in aerospace-grade titanium with all-day battery life.",
        price: "Available on request",
        badge: "Special Order",
        image: "/products/campaigns/iphone-18-pro-colors.webp",
        alt: "iPhone 18 Pro titanium finishes",
        buyPath: "/shop/buy-iphone/iphone-18-pro",
        buyLabel: "View Pricing",
        storyPath: "/iphone/iphone-18-pro",
        storyLabel: "Learn more",
        isDark: true,
      },
      {
        id: "iphone-duo",
        eyebrow: "DUAL DISPLAY INNOVATION",
        title: "iPhone Duo",
        subtitle: "Foldable dual-display format engineered for expansive reading, media, and multitasking.",
        price: "Available on request",
        badge: "New Concept",
        image: "/products/homepage/iphone-duo.webp",
        alt: "iPhone Duo dual-screen foldable phone",
        buyPath: "/shop/buy-iphone/iphone-duo",
        buyLabel: "View Pricing",
        storyPath: "/iphone/iphone-duo",
        storyLabel: "Learn more",
        isViewPricingOnly: true,
        isDark: false,
      },
      {
        id: "iphone-16-pro-max",
        eyebrow: "PRO MAX POWER",
        title: "iPhone 16 Pro Max",
        subtitle: "6.9-inch Super Retina XDR display, A18 Pro chip, and 48MP Fusion camera system.",
        price: "From GH₵ 19,800",
        badge: "In Stock",
        image: localCatalogueImageBySlug["iphone-16-pro-max"],
        alt: "iPhone 16 Pro Max display and titanium finish",
        buyPath: "/shop/buy-iphone/iphone-16-pro-max",
        buyLabel: "Buy",
        storyPath: "/shop/buy-iphone/iphone-16-pro-max",
        storyLabel: "Details",
        isDark: false,
      },
      {
        id: "iphone-15-pro-max",
        eyebrow: "POPULAR UK USED",
        title: "iPhone 15 Pro Max",
        subtitle: "Grade-5 titanium design with Action button, USB-C connectivity, and 5x Telephoto zoom.",
        price: "From GH₵ 14,500",
        badge: "Verified Grade A",
        image: localCatalogueImageBySlug["iphone-15-pro-max"],
        alt: "iPhone 15 Pro Max premium titanium",
        buyPath: "/shop/buy-iphone/iphone-15-pro-max",
        buyLabel: "Buy",
        storyPath: "/shop/buy-iphone/iphone-15-pro-max",
        storyLabel: "Details",
        isDark: false,
      },
      {
        id: "iphone-13-pro-max",
        eyebrow: "VALUE FAVORITE",
        title: "iPhone 13 Pro Max",
        subtitle: "Super Retina XDR with ProMotion 120Hz, A15 Bionic performance, and exceptional battery stamina.",
        price: "From GH₵ 8,500",
        badge: "UK Used",
        image: localCatalogueImageBySlug["iphone-13-pro-max"],
        alt: "iPhone 13 Pro Max flagship phone",
        buyPath: "/shop/buy-iphone/iphone-13-pro-max",
        buyLabel: "Buy",
        storyPath: "/shop/buy-iphone/iphone-13-pro-max",
        storyLabel: "Details",
        isDark: false,
      },
    ],
    catalogTitle: "All iPhone Listings.",
    catalogSubtitle: "Real Buy & Sell GH store listings with verified storage, cosmetic grading, and confirmed battery health.",
    storeCategoryFilter: "Phones",
  },

  mac: {
    key: "mac",
    label: "Mac",
    tagline: "Power for every workflow. Beautifully focused.",
    description: "Explore MacBook Air, MacBook Pro, and Apple silicon desktop workstations with verified Accra availability and warranty support.",
    seoTitle: "Shop Mac & MacBooks | Buy & Sell GH Store",
    seoDescription: "Discover MacBook Air, MacBook Pro, Mac mini and Mac Studio in Ghana. Verified Apple Silicon performance, memory configurations, and warranty.",
    subnavItems: [
      { id: "all", label: "All Mac" },
      { id: "macbook-air", label: "MacBook Air" },
      { id: "macbook-pro", label: "MacBook Pro" },
      { id: "mac-mini", label: "Mac mini" },
      { id: "mac-studio", label: "Mac Studio" },
    ],
    featuredCards: [
      {
        id: "macbook-air-15",
        eyebrow: "STRIKINGLY THIN",
        title: "MacBook Air 15”",
        subtitle: "Spacious Liquid Retina display with M3/M4 chip efficiency and up to 18 hours of battery life.",
        price: "From GH₵ 18,500",
        badge: "Popular Pick",
        image: localCatalogueImageBySlug["macbook-air-15-m4"],
        alt: "MacBook Air 15-inch (M4)",
        buyPath: "/shop/buy-mac/macbook-air-15-m4",
        buyLabel: "Buy",
        storyPath: "/mac/macbook-air",
        storyLabel: "Learn more",
        isDark: false,
      },
      {
        id: "macbook-pro-16",
        eyebrow: "EXTREME PRO POWER",
        title: "MacBook Pro 16”",
        subtitle: "Liquid Retina XDR display with M4 Pro and M4 Max chips for demanding creative and engineering tasks.",
        price: "From GH₵ 32,000",
        badge: "Workstation",
        image: localCatalogueImageBySlug["macbook-pro-16-m4-pro-max"],
        alt: "MacBook Pro 16-inch (M4 Pro / M4 Max)",
        buyPath: "/shop/buy-mac/macbook-pro-16-inch-m4-pro-max",
        buyLabel: "Buy",
        storyPath: "/shop/buy-mac/macbook-pro-16-inch-m4-pro-max",
        storyLabel: "Details",
        isDark: false,
      },
      {
        id: "macbook-pro-14",
        eyebrow: "COMPACT PRO",
        title: "MacBook Pro 14”",
        subtitle: "Phenomenal pro performance in a portable chassis with HDMI, MagSafe 3, and SDXC card reader.",
        price: "From GH₵ 22,000",
        badge: "In Stock",
        image: localCatalogueImageBySlug["macbook-pro-14-m4"],
        alt: "MacBook Pro 14 inch",
        buyPath: "/shop/buy-mac/macbook-pro-14-m4",
        buyLabel: "Buy",
        storyPath: "/shop/buy-mac/macbook-pro-14-m4",
        storyLabel: "Details",
        isDark: false,
      },
      {
        id: "macbook-air-13",
        eyebrow: "PORTABLE EVERYDAY",
        title: "MacBook Air 13”",
        subtitle: "Silent, fanless enclosure built for work, university, and mobility on a single battery charge.",
        price: "From GH₵ 13,500",
        badge: "Bestseller",
        image: localCatalogueImageBySlug["macbook-air-13-m3"],
        alt: "MacBook Air 13 inch",
        buyPath: "/shop/buy-mac/macbook-air-13-m3",
        buyLabel: "Buy",
        storyPath: "/mac/macbook-air",
        storyLabel: "Learn more",
        isDark: false,
      },
      {
        id: "mac-mini",
        eyebrow: "DESKTOP CONCENTRATION",
        title: "Mac mini",
        subtitle: "Compact Apple silicon desktop offering incredible processing throughput in a minimal desk footprint.",
        price: "From GH₵ 9,800",
        badge: "New Architecture",
        image: "/products/homepage/mac-mini.jpg",
        alt: "Apple Mac mini compact desktop",
        buyPath: "/mac-mini",
        buyLabel: "View Pricing",
        storyPath: "/mac-mini",
        storyLabel: "Explore",
        isDark: false,
      },
      {
        id: "mac-studio",
        eyebrow: "CREATIVE HEAVYWEIGHT",
        title: "Mac Studio",
        subtitle: "Massive CPU and GPU horsepower engineered for 3D rendering, complex code compiling, and 8K video.",
        price: "Available on request",
        badge: "Special Order",
        image: macStudioLaunchImage,
        alt: "Mac Studio workstation",
        buyPath: "/mac-studio",
        buyLabel: "View Pricing",
        storyPath: "/mac-studio",
        storyLabel: "Explore",
        isDark: false,
      },
    ],
    catalogTitle: "All Mac Listings.",
    catalogSubtitle: "Confirmed MacBook Air and MacBook Pro notebooks with verified memory, SSD capacities, and battery cycles.",
    storeCategoryFilter: "Laptops",
  },

  ipad: {
    key: "ipad",
    label: "iPad",
    tagline: "Touch, draw, and type on one versatile canvas.",
    description: "Compare iPad models for university study, digital illustration, office workflows, and portable entertainment.",
    seoTitle: "Shop iPad | Buy & Sell GH Store",
    seoDescription: "Explore iPad Pro, iPad Air, iPad 10th Gen and iPad mini in Ghana. Genuine Apple hardware, accessories, and local support in Accra.",
    subnavItems: [
      { id: "all", label: "All iPad" },
      { id: "ipad-pro", label: "iPad Pro" },
      { id: "ipad-air", label: "iPad Air" },
      { id: "ipad-standard", label: "iPad (Standard)" },
      { id: "ipad-mini", label: "iPad mini" },
    ],
    featuredCards: [
      {
        id: "ipad-pro-13",
        eyebrow: "TANDEM OLED DISPLAY",
        title: "iPad Pro 13”",
        subtitle: "Groundbreaking Ultra Retina XDR display with pro Apple M4 silicon and Apple Pencil Pro support.",
        price: "From GH₵ 21,500",
        badge: "Flagship",
        image: localCatalogueImageBySlug["ipad-pro-13-inch-m4"],
        alt: "iPad Pro 13 Space Black",
        buyPath: "/shop/buy-ipad/ipad-pro-13-inch-m4",
        buyLabel: "Buy",
        storyPath: "/shop/buy-ipad/ipad-pro-13-inch-m4",
        storyLabel: "Details",
        isDark: false,
      },
      {
        id: "ipad-air-colors",
        eyebrow: "TWO SIZES. FRESH STYLES.",
        title: "iPad Air",
        subtitle: "Brilliant Liquid Retina screen in 11-inch and 13-inch models powered by Apple M2 and M4 chips.",
        price: "From GH₵ 12,800",
        badge: "Popular Pick",
        image: "/products/campaigns/ipad-air-colors.webp",
        alt: "iPad Air multi-color lineup",
        buyPath: "/shop/buy-ipad/ipad-air",
        buyLabel: "Buy",
        storyPath: "/ipad/ipad-air",
        storyLabel: "Learn more",
        isDark: false,
      },
      {
        id: "ipad-mini-7",
        eyebrow: "POCKETABLE POWERHOUSE",
        title: "iPad mini",
        subtitle: "8.3-inch edge-to-edge Liquid Retina canvas with A17 Pro performance and Apple Pencil Pro compatibility.",
        price: "From GH₵ 8,900",
        badge: "Ultra-Portable",
        image: localCatalogueImageBySlug["ipad-mini-a17-pro"],
        alt: "iPad mini portable tablet",
        buyPath: "/shop/buy-ipad/ipad-mini-a17-pro",
        buyLabel: "Buy",
        storyPath: "/shop/buy-ipad/ipad-mini-a17-pro",
        storyLabel: "Details",
        isDark: false,
      },
      {
        id: "ipad-10th-gen",
        eyebrow: "COLOURFUL ALL-ROUNDER",
        title: "iPad (10th gen)",
        subtitle: "All-screen design with 10.9-inch Liquid Retina display, A14 Bionic, USB-C, and landscape stereo speakers.",
        price: "From GH₵ 6,200",
        badge: "Value Pick",
        image: localCatalogueImageBySlug["ipad-10th-generation"],
        alt: "iPad 10th generation tablet",
        buyPath: "/shop/buy-ipad/ipad-10th-generation",
        buyLabel: "Buy",
        storyPath: "/shop/buy-ipad/ipad-10th-generation",
        storyLabel: "Details",
        isDark: false,
      },
    ],
    catalogTitle: "All iPad Listings.",
    catalogSubtitle: "Real listed iPad configurations across storage tiers, Wi-Fi and Cellular models, and verified cosmetic conditions.",
    storeCategoryFilter: "Tablets",
  },

  watch: {
    key: "watch",
    label: "Apple Watch",
    tagline: "The ultimate device for a healthy, connected life.",
    description: "Explore Apple Watch Ultra, Series, and SE with verified local stock, wrist sizes, and genuine band options.",
    seoTitle: "Shop Apple Watch | Buy & Sell GH Store",
    seoDescription: "Browse Apple Watch Ultra, Series 12 & 11, and SE in Ghana. Advanced health sensors, GPS + Cellular connectivity, and Accra delivery.",
    subnavItems: [
      { id: "all", label: "All Watches" },
      { id: "ultra", label: "Apple Watch Ultra" },
      { id: "series", label: "Apple Watch Series" },
      { id: "se", label: "Apple Watch SE" },
    ],
    featuredCards: [
      {
        id: "watch-ultra-4",
        eyebrow: "RUGGED TITANIUM",
        title: "Apple Watch Ultra 4",
        subtitle: "49mm corrosion-resistant aerospace titanium case, dual-frequency GPS, and 100m water resistance.",
        price: "From GH₵ 12,500",
        badge: "Adventure Pick",
        image: "/products/homepage/watch-ultra-4.webp",
        alt: "Apple Watch Ultra 4 rugged titanium watch",
        buyPath: "/shop/buy-watch/apple-watch-ultra-4",
        buyLabel: "Buy",
        storyPath: "/watch/apple-watch-ultra-4",
        storyLabel: "Learn more",
        isDark: true,
      },
      {
        id: "watch-series-12",
        eyebrow: "SLIMMER. WIDER DISPLAY.",
        title: "Apple Watch Series 12",
        subtitle: "Wide-angle OLED display, advanced ECG and sleep monitoring, depth sensor, and fast magnetic charging.",
        price: "From GH₵ 7,200",
        badge: "Everyday Hero",
        image: "/products/homepage/watch-series-12.webp",
        alt: "Apple Watch Series 12 smartwatch",
        buyPath: "/shop/buy-watch/apple-watch-series-12",
        buyLabel: "Buy",
        storyPath: "/watch/apple-watch-series-12",
        storyLabel: "Learn more",
        isDark: false,
      },
      {
        id: "watch-se",
        eyebrow: "ESSENTIAL FITNESS",
        title: "Apple Watch SE",
        subtitle: "Crash Detection, workout metrics, heart rate notifications, and water resistance up to 50 meters.",
        price: "From GH₵ 4,200",
        badge: "Smart Value",
        image: localCatalogueImageBySlug["apple-watch-se-3"],
        alt: "Apple Watch SE fitness watch",
        buyPath: "/shop/buy-watch/apple-watch-se-3",
        buyLabel: "Buy",
        storyPath: "/shop/buy-watch/apple-watch-se-3",
        storyLabel: "Details",
        isDark: false,
      },
    ],
    catalogTitle: "All Apple Watch Listings.",
    catalogSubtitle: "Available Apple Watch hardware with verified case sizing (40mm to 49mm), battery health, and pairing guarantee.",
    storeCategoryFilter: "Watches",
  },

  airpods: {
    key: "airpods",
    label: "AirPods",
    tagline: "Wireless sound, engineered for effortless listening.",
    description: "Explore AirPods Pro with active noise cancellation, versatile AirPods 5, and high-fidelity AirPods Max.",
    seoTitle: "Shop AirPods & Audio | Buy & Sell GH Store",
    seoDescription: "Discover original AirPods, AirPods Pro 2, and AirPods Max in Ghana. Verified original Apple audio hardware and local Accra warranty.",
    subnavItems: [
      { id: "all", label: "All AirPods" },
      { id: "pro", label: "AirPods Pro" },
      { id: "standard", label: "AirPods 5 & 4" },
      { id: "max", label: "AirPods Max" },
    ],
    featuredCards: [
      {
        id: "airpods-pro-2",
        eyebrow: "ACTIVE NOISE CANCELLATION",
        title: "AirPods Pro (2nd gen)",
        subtitle: "Up to 2x more active noise cancellation, Adaptive Audio, Conversation Awareness, and USB-C MagSafe case.",
        price: "GH₵ 2,200",
        badge: "In Stock",
        image: localCatalogueImageBySlug["airpods-pro-2"],
        alt: "AirPods Pro charging case and earbuds",
        buyPath: "/shop/buy-airpods/airpods-pro-2",
        buyLabel: "Buy",
        storyPath: "/shop/buy-airpods/airpods-pro-2",
        storyLabel: "Details",
        isDark: false,
      },
      {
        id: "airpods-5",
        eyebrow: "REFINED ACOUSTICS",
        title: "AirPods 5",
        subtitle: "Open-ear comfort with rich bass, crystal-clear high frequencies, and personalized Spatial Audio.",
        price: "From GH₵ 1,800",
        badge: "New Release",
        image: "/products/homepage/airpods-5.jpg",
        alt: "AirPods 5 wireless earbuds",
        buyPath: "/shop/buy-airpods/airpods-5",
        buyLabel: "Buy",
        storyPath: "/airpods/airpods-5",
        storyLabel: "Learn more",
        isDark: false,
      },
      {
        id: "airpods-max",
        eyebrow: "HIGH-FIDELITY OVER-EAR",
        title: "AirPods Max",
        subtitle: "Custom acoustic design, computational audio, pro-level active noise cancellation, and USB-C charging.",
        price: "From GH₵ 8,500",
        badge: "Studio Audio",
        image: localCatalogueImageBySlug["airpods-max-2"],
        alt: "AirPods Max premium over-ear headphones",
        buyPath: "/shop/buy-airpods/airpods-max-2",
        buyLabel: "Buy",
        storyPath: "/shop/buy-airpods/airpods-max-2",
        storyLabel: "Details",
        isDark: false,
      },
    ],
    catalogTitle: "All AirPods Listings.",
    catalogSubtitle: "Authentic Apple wireless audio hardware with confirmed case generations, USB-C ports, and serial verification.",
    storeCategoryFilter: "Audio",
  },

  accessories: {
    key: "accessories",
    label: "Accessories",
    tagline: "Essential power, protection, and input companions.",
    description: "Browse original Apple chargers, MagSafe adapters, braided cables, Magic Keyboards, and protective cases.",
    seoTitle: "Shop Apple Accessories | Buy & Sell GH Store",
    seoDescription: "Original Apple adapters, MagSafe chargers, Magic Keyboard, Magic Mouse, and Pencil Pro in Ghana. Confirmed compatibility and fast delivery.",
    subnavItems: [
      { id: "all", label: "All Accessories" },
      { id: "charging", label: "Charging & Power" },
      { id: "magsafe", label: "MagSafe" },
      { id: "cables", label: "Cables" },
      { id: "input", label: "Keyboards & Pointers" },
    ],
    featuredCards: [
      {
        id: "magsafe-charger-puck",
        eyebrow: "FAST WIRELESS CHARGING",
        title: "Apple MagSafe Charger",
        subtitle: "Snaps magnetically to iPhone and AirPods for seamless, efficient wireless charging up to 25W.",
        price: "Contact for price",
        badge: "Original Apple",
        image: "/products/campaigns/accessory-magsafe-puck.webp",
        alt: "Apple MagSafe charger puck with braided cable",
        buyPath: "/shop/buy-accessory/apple-magsafe-charger",
        buyLabel: "View Pricing",
        storyPath: "/accessories/charging-and-power",
        storyLabel: "Learn more",
        isDark: false,
      },
      {
        id: "adapter-20w",
        eyebrow: "EVERYDAY ESSENTIAL",
        title: "20W USB-C Power Adapter",
        subtitle: "Compact, fast, and energy-efficient charging for iPhone, iPad, and Apple Watch.",
        price: "Contact for price",
        badge: "Availability to confirm",
        image: "",
        alt: "Apple 20W USB-C Power Adapter",
        buyPath: "/shop/buy-accessory/apple-20w-usb-c-power-adapter",
        buyLabel: "View Pricing",
        storyPath: "/shop/buy-accessory/apple-20w-usb-c-power-adapter",
        storyLabel: "Details",
        isDark: false,
      },
      {
        id: "magic-keyboard-touchid",
        eyebrow: "BIOMETRIC PRODUCTIVITY",
        title: "Magic Keyboard with Touch ID",
        subtitle: "Fast, easy authentication and secure password entry in a sleek, rechargeable wireless keyboard.",
        price: "Contact for price",
        badge: "Mac Companion",
        image: localCatalogueImageBySlug["apple-magic-keyboard-touch-id"],
        alt: "Apple Magic Keyboard for Mac",
        buyPath: "/shop/buy-accessory/apple-magic-keyboard-touch-id",
        buyLabel: "View Pricing",
        storyPath: "/shop/buy-accessory/apple-magic-keyboard-touch-id",
        storyLabel: "Details",
        isDark: false,
      },
      {
        id: "adapter-140w",
        eyebrow: "HIGH OUTPUT POWER",
        title: "140W USB-C Power Adapter",
        subtitle: "Supports fast-charging up to 50 percent in around 30 minutes on supported 16-inch MacBook Pro models.",
        price: "Contact for price",
        badge: "Heavy Duty",
        image: localCatalogueImageBySlug["apple-140w-usb-c-power-adapter"],
        alt: "Apple 140W USB-C Power Adapter",
        buyPath: "/shop/buy-accessory/apple-140w-usb-c-power-adapter",
        buyLabel: "View Pricing",
        storyPath: "/shop/buy-accessory/apple-140w-usb-c-power-adapter",
        storyLabel: "Details",
        isDark: false,
      },
    ],
    catalogTitle: "All Accessory Listings.",
    catalogSubtitle: "Genuine Apple power bricks, braided cords, input peripherals, and protection verified by the Buy & Sell GH team.",
    storeCategoryFilter: "Accessories",
  },
};
